[font]
size = 14

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[window]
opacity = 1
startup_mode = "Maximized"

[keyboard]
bindings = [
  { key = "Slash", mods = "Control", chars = "\u001f" },
]
